### ISSUE TITLE
CI workflow infra automatic cleanup

### ISSUE THREAD

**Issue by horiagunica** [PaloAltoNetworks/terraform-azurerm-swfw-modules#143]
### Is your feature request related to a problem?

- [tf_test](https://github.com/PaloAltoNetworks/terraform-modules-swfw-ci-workflows/blob/v2.2/.github/workflows/_tf_test.yml) CI workflow doesn't have any automatic way to cleanup.

### Describe the solution you'd like

- Implement a cleanup mechanism in case of CI cancellation/failure.

**Comment by acelebanski** [comment]
Hi @horiagunica, do you suggest that this piece of code doesn't work as expected?

```
      - name: cleanup Azure Subscription
        if: inputs.cloud == 'azure'
        uses: ./.github/actions/sub_cleanup
        with:
          pr-id: ${{ inputs.pr-id }}
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
```
